name: staging

on:
  push:
    branches:
      - staging

env:
  AWS_REGION: eu-south-1

jobs:
  showcase-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18.16.0"
        cache: "yarn"

    - name: Install dependencies
      run: yarn install --immutable

    - name: Run Ketchup build
      run: npm run k:build

    - name: Run Ketchup Showcase build
      run: npm run ksc:build
    
    - name: Setup AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload artifacts to AWS S3
      run: aws s3 sync packages/ketchup-showcase/dist/ s3://smeup-ketchup/staging/ --delete